server:
  port: 8080

spring:
  application.name: db-hierarchy
  profiles:
    include: database
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        use_sql_comments: true
